# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_auto_20160404_1652'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
    ]

    operations = [
    ]
